openapi: 3.0.1
info:
  title: Todo Chatbot API
  description: API for AI-powered todo chatbot functionality
  version: 1.0.0
paths:
  /api/chat:
    post:
      summary: Process natural language chat message
      description: Handles user chat input and returns AI response with tool execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: integer
                  description: Optional conversation ID to continue existing conversation
                  example: 1
                message:
                  type: string
                  description: User's natural language message
                  example: "Add a task to buy groceries"
              required:
                - message
      responses:
        '200':
          description: Successful response from AI assistant
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: ID of the conversation (new or existing)
                    example: 1
                  response:
                    type: string
                    description: AI assistant's response
                    example: "I've added 'Buy groceries' to your tasks."
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        tool:
                          type: string
                          description: Name of the tool called
                          example: "add_task"
                        task_id:
                          type: integer
                          description: ID of the task affected (if applicable)
                          example: 5
                        status:
                          type: string
                          description: Status of the operation
                          example: "success"
        '400':
          description: Bad request - invalid input
        '401':
          description: Unauthorized - invalid or missing JWT token
        '500':
          description: Internal server error
      security:
        - BearerAuth: []
  /api/conversations:
    get:
      summary: List user's conversations
      description: Retrieve all conversations for the authenticated user
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Grocery tasks"
                    created_at:
                      type: string
                      format: date-time
                      example: "2026-01-14T10:00:00Z"
                    updated_at:
                      type: string
                      format: date-time
                      example: "2026-01-14T10:05:00Z"
        '401':
          description: Unauthorized - invalid or missing JWT token
      security:
        - BearerAuth: []
  /api/conversations/{conversation_id}/messages:
    get:
      summary: Get messages for a conversation
      description: Retrieve all messages for a specific conversation
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    role:
                      type: string
                      enum: [user, assistant]
                      example: "user"
                    content:
                      type: string
                      example: "Add a task to buy groceries"
                    created_at:
                      type: string
                      format: date-time
                      example: "2026-01-14T10:00:00Z"
        '401':
          description: Unauthorized - invalid or missing JWT token
        '403':
          description: Forbidden - user doesn't have access to this conversation
        '404':
          description: Not found - conversation doesn't exist
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT